introduce a test (i deliberately changed the price to see if equal
goes into the structure)

[martin@localhost source00]$ go test
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /albums                   --> mymain.getAlbums (3 handlers)
[GIN] 2022/09/17 - 09:03:22 | 200 |      72.191µs |                 | GET      "/albums"
--- FAIL: Test_getAlbums (0.00s)
    01_mymain_unit_test.go:28:
        	Error Trace:	01_mymain_unit_test.go:28
        	Error:      	Not equal:
        	            	expected: []mymain.album{mymain.album{ID:"1", Title:"blue train", Artist:"john coltrane", Price:54.99}, mymain.album{ID:"2", Title:"jeru", Artist:"eryy muliiang", Price:17.99}, mymain.album{ID:"3", Title:"vaun and brown", Artist:"vaaughn", Price:39.99}}
        	            	actual  : []mymain.album{mymain.album{ID:"1", Title:"blue train", Artist:"john coltrane", Price:54.99}, mymain.album{ID:"2", Title:"jeru", Artist:"eryy muliiang", Price:17.99}, mymain.album{ID:"3", Title:"vaun and brown", Artist:"vaaughn", Price:39.91}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -17,3 +17,3 @@
        	            	   Artist: (string) (len=7) "vaaughn",
        	            	-  Price: (float64) 39.99
        	            	+  Price: (float64) 39.91
        	            	  }
        	Test:       	Test_getAlbums
FAIL
exit status 1
FAIL	mymain	0.010s