lots of mistakes
 ⚙ martin@x201minyi  ~/stage/cl-golang-generator/examples/08_fayne_gui_fractal/source   master ●  go build fractal.go
./fractal.go:27:10: f.NewSize undefined (type *fractal has no field or method NewSize)
./fractal.go:33:20: cannot use uint(100 * (1 + math.Pow(math.Log10(1 / currScale), 1.25))) (type uint) as type int in assignment
./fractal.go:33:72: undefined: currScale
./fractal.go:44:13: assignment mismatch: 3 variables but start.RGBA returns 4 values
./fractal.go:45:13: assignment mismatch: 3 variables but end.RGBA returns 4 values
./fractal.go:66:3: cannot use theme.BackgroundColor (type func() color.Color) as type color.Color in return argument:
        func() color.Color does not implement color.Color (missing RGBA method)
./fractal.go:68:25: undefined: flaot64